### ISSUE TITLE
Circular dependency when including augeas

### ISSUE THREAD

**Issue by avanrielly** [boxen/puppet-augeas#1] opened 2013-06-21 20:26 UTC
I have added augeas to my puppetfile, but I get a circular dependency when I include it in my site.pp.

def github(name, version, options = nil)
  options ||= {}
  options[:repo] ||= "boxen/puppet-#{name}"
  mod name, version, :github_tarball => options[:repo]
end
github "augeas",            "1.2.0"

Error: Could not apply complete catalog: Found 1 dependency cycle:
(File[/opt/boxen/homebrew/Library/Taps/boxen-brews/augeas.rb] => Homebrew::Formula[augeas] => Package[pkg-config] => Class[Pkgconfig] => Class[Augeas] => Homebrew::Formula[augeas] => File[/opt/boxen/homebrew/Library/Taps/boxen-brews/augeas.rb])

**Comment by skottler** [comment] 2014-05-18 12:24
I can't reproduce this anymore. Sorry this never really got responded to, going to close it out.

**Closed as completed by skottler** 2014-05-18 12:24 UTC
